""" Global Flask Application Settings """

import os


class Config(object):
    DEBUG = False
    TESTING = False
    BASE_DIR = os.path.dirname(__file__)
    CLIENT_DIR = os.path.join(BASE_DIR, 'client')

    if not os.path.exists(CLIENT_DIR):
        raise Exception(
            'Client App directory not found: {}'.format(CLIENT_DIR))


secret_key = '7OAo2H0ZUq9byrHBuBgnFzCOg2W3fk9o' # Generated by shell command `cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`


# Different modes:


class Development(Config):
    DEBUG = True
    PRODUCTION = False
    SECRET_KEY = 'SuperSecretKey'


class Production(Config):
    DEBUG = False
    PRODUCTION = True
    SECRET_KEY = os.environ.get('SECRET_KEY', secret_key)


def current_mode():
    return os.environ.get('FLASK_CONFIG', 'Development') # Set `FLASK_CONFIG` env var to 'Production' or 'Development' to alter Config
